export const FETCH_ALL_BLOGS_REQUEST = 'FETCH_ALL_BLOGS_REQUEST'
export const FETCH_ALL_BLOGS_SUCCESS = 'FETCH_ALL_BLOGS_SUCCESS'
export const FETCH_ALL_BLOGS_FAILURE = 'FETCH_ALL_BLOGS_FAILURE'

export const FETCH_SINGLE_BLOG_REQUEST = 'FETCH_SINGLE_BLOG_REQUEST'
export const FETCH_SINGLE_BLOG_SUCCESS = 'FETCH_SINGLE_BLOG_SUCCESS'
export const FETCH_SINGLE_BLOG_FAILURE = 'FETCH_SINGLE_BLOG_FAILURE'
